/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;
import model.dictionary;
import model.history;

/**
 *
 * @author holohoi
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Index() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        Navside = new javax.swing.JPanel();
        Navlink1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Navlink2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Navlink3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Navlink4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        SearchBody = new javax.swing.JPanel();
        ActionBtn = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        historyBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        randomBtn = new javax.swing.JButton();
        ActionPanel = new javax.swing.JPanel();
        EditActionPanel = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textInputWordEdit = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textInputDefinitionEdit = new javax.swing.JTextArea();
        SaveEdit = new javax.swing.JButton();
        SearchActionPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        SearchByComboBox = new javax.swing.JComboBox<>();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textInputSearch = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textOutputSearch = new javax.swing.JTextPane();
        HistoryActionPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textOutputHistory = new javax.swing.JTextArea();
        AddNewWordBody = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textInputWordAdd = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textInputDefinitionAdd = new javax.swing.JTextArea();
        QuizBody = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        textPaneQuestion = new javax.swing.JTextPane();
        jPanel21 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        answerA = new javax.swing.JToggleButton();
        jPanel24 = new javax.swing.JPanel();
        answerC = new javax.swing.JToggleButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        typeOfQuizComboBox = new javax.swing.JComboBox<>();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        answerB = new javax.swing.JToggleButton();
        jPanel28 = new javax.swing.JPanel();
        answerD = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        textScore = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        checkAnswerBtn = new javax.swing.JButton();
        checkAnsPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        textOutputCheckAnswer = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(26, 15, 15));

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SLANG WORD");

        resetBtn.setBackground(new java.awt.Color(208, 228, 86));
        resetBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(0, 0, 0));
        resetBtn.setText("Reset to original");
        resetBtn.setBorder(new RoundBtn(30));
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Navside.setBackground(new java.awt.Color(96, 73, 73));
        Navside.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Navlink1.setBackground(new java.awt.Color(58, 39, 112));
        Navlink1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), null), null));
        Navlink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Navlink1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Search");

        javax.swing.GroupLayout Navlink1Layout = new javax.swing.GroupLayout(Navlink1);
        Navlink1.setLayout(Navlink1Layout);
        Navlink1Layout.setHorizontalGroup(
            Navlink1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Navlink1Layout.setVerticalGroup(
            Navlink1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Navlink2.setBackground(new java.awt.Color(58, 39, 112));
        Navlink2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), null), null));
        Navlink2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Navlink2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Add a new word");

        javax.swing.GroupLayout Navlink2Layout = new javax.swing.GroupLayout(Navlink2);
        Navlink2.setLayout(Navlink2Layout);
        Navlink2Layout.setHorizontalGroup(
            Navlink2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Navlink2Layout.setVerticalGroup(
            Navlink2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Navlink3.setBackground(new java.awt.Color(58, 39, 112));
        Navlink3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), null), null));
        Navlink3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Navlink3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Quiz by word");

        javax.swing.GroupLayout Navlink3Layout = new javax.swing.GroupLayout(Navlink3);
        Navlink3.setLayout(Navlink3Layout);
        Navlink3Layout.setHorizontalGroup(
            Navlink3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        Navlink3Layout.setVerticalGroup(
            Navlink3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Navlink4.setBackground(new java.awt.Color(58, 39, 112));
        Navlink4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), null), null));
        Navlink4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Navlink4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Quiz by definition");

        javax.swing.GroupLayout Navlink4Layout = new javax.swing.GroupLayout(Navlink4);
        Navlink4.setLayout(Navlink4Layout);
        Navlink4Layout.setHorizontalGroup(
            Navlink4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Navlink4Layout.setVerticalGroup(
            Navlink4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navlink4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NavsideLayout = new javax.swing.GroupLayout(Navside);
        Navside.setLayout(NavsideLayout);
        NavsideLayout.setHorizontalGroup(
            NavsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavsideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Navlink2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Navlink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Navlink3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Navlink4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        NavsideLayout.setVerticalGroup(
            NavsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavsideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Navlink1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Navlink2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Navlink3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Navlink4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Body.setBackground(new java.awt.Color(170, 189, 172));

        SearchBody.setBackground(new java.awt.Color(170, 189, 172));
        SearchBody.setLayout(new java.awt.BorderLayout());
        SearchBody.setVisible(true);

        ActionBtn.setBackground(new java.awt.Color(170, 189, 172));

        jPanel8.setBackground(new java.awt.Color(118, 65, 65));

        historyBtn.setBackground(new java.awt.Color(255, 243, 210));
        historyBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        historyBtn.setForeground(new java.awt.Color(0, 0, 0));
        historyBtn.setText("History");
        historyBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        historyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyBtnMouseClicked(evt);
            }
        });
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });
        resetBtn.setBorder(new RoundBtn(30));

        editBtn.setBackground(new java.awt.Color(236, 224, 255));
        editBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 0, 0));
        editBtn.setText("Edit this word");
        editBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        resetBtn.setBorder(new RoundBtn(30));

        deleteBtn.setBackground(new java.awt.Color(0, 255, 194));
        deleteBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn.setText("Delete this word");
        deleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        resetBtn.setBorder(new RoundBtn(30));

        randomBtn.setBackground(new java.awt.Color(230, 249, 115));
        randomBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        randomBtn.setForeground(new java.awt.Color(0, 0, 0));
        randomBtn.setText("Random a slang word");
        randomBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        randomBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                randomBtnMouseClicked(evt);
            }
        });
        randomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomBtnActionPerformed(evt);
            }
        });
        resetBtn.setBorder(new RoundBtn(30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(randomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(randomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ActionBtnLayout = new javax.swing.GroupLayout(ActionBtn);
        ActionBtn.setLayout(ActionBtnLayout);
        ActionBtnLayout.setHorizontalGroup(
            ActionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ActionBtnLayout.setVerticalGroup(
            ActionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionBtnLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SearchBody.add(ActionBtn, java.awt.BorderLayout.PAGE_END);

        ActionPanel.setBackground(new java.awt.Color(170, 189, 172));

        EditActionPanel.setLayout(new java.awt.GridLayout(1, 0));
        EditActionPanel.setVisible(false);

        jPanel16.setBackground(new java.awt.Color(170, 189, 172));

        jPanel17.setBackground(new java.awt.Color(255, 155, 113));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel17.setForeground(new java.awt.Color(255, 155, 113));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Slang word");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        textInputWordEdit.setBackground(new java.awt.Color(255, 255, 255));
        textInputWordEdit.setColumns(20);
        textInputWordEdit.setRows(5);
        textInputWordEdit.setFont( textInputWordEdit.getFont().deriveFont(textInputWordEdit.getFont().getSize() + 5.0f) );
        jScrollPane5.setViewportView(textInputWordEdit);

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Back to search");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        EditActionPanel.add(jPanel16);

        jPanel18.setBackground(new java.awt.Color(170, 189, 172));

        jPanel19.setBackground(new java.awt.Color(255, 155, 113));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel19.setForeground(new java.awt.Color(255, 155, 113));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Definition");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));

        textInputDefinitionEdit.setBackground(new java.awt.Color(255, 255, 255));
        textInputDefinitionEdit.setColumns(20);
        textInputDefinitionEdit.setRows(5);
        textInputDefinitionEdit.setFont( textInputDefinitionEdit.getFont().deriveFont(textInputDefinitionEdit.getFont().getSize() + 5.0f) );
        jScrollPane6.setViewportView(textInputDefinitionEdit);

        SaveEdit.setBackground(new java.awt.Color(102, 255, 102));
        SaveEdit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SaveEdit.setForeground(new java.awt.Color(0, 0, 0));
        SaveEdit.setText("Save");
        SaveEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaveEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveEdit)
                .addContainerGap())
        );

        EditActionPanel.add(jPanel18);

        SearchActionPanel.setLayout(new java.awt.BorderLayout());
        SearchActionPanel.setVisible(true);

        jPanel4.setBackground(new java.awt.Color(170, 189, 172));

        jPanel1.setBackground(new java.awt.Color(255, 155, 113));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search by");

        SearchByComboBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SearchByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slang word", "Definition" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchByComboBox, 0, 132, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchByComboBox)
                .addGap(4, 4, 4))
        );

        SearchBtn.setBackground(new java.awt.Color(255, 255, 102));
        SearchBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(0, 0, 0));
        SearchBtn.setText("Search");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        textInputSearch.setColumns(20);
        textInputSearch.setRows(5);
        jScrollPane1.setViewportView(textInputSearch);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchBtn)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        SearchActionPanel.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(170, 189, 172));

        textOutputSearch.setFont( textOutputSearch.getFont().deriveFont(textOutputSearch.getFont().getSize() + 5.0f) );
        jScrollPane7.setViewportView(textOutputSearch);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        SearchActionPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        HistoryActionPanel.setBackground(new java.awt.Color(170, 189, 172));
        HistoryActionPanel.setVisible(false);

        jButton4.setBackground(new java.awt.Color(255, 255, 153));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Back to search");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        textOutputHistory.setEditable(false);
        textOutputHistory.setColumns(20);
        textOutputHistory.setRows(5);
        textOutputHistory.setFont( textOutputHistory.getFont().deriveFont(textOutputHistory.getFont().getSize() + 5.0f) );
        jScrollPane2.setViewportView(textOutputHistory);

        javax.swing.GroupLayout HistoryActionPanelLayout = new javax.swing.GroupLayout(HistoryActionPanel);
        HistoryActionPanel.setLayout(HistoryActionPanelLayout);
        HistoryActionPanelLayout.setHorizontalGroup(
            HistoryActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HistoryActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        HistoryActionPanelLayout.setVerticalGroup(
            HistoryActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout ActionPanelLayout = new javax.swing.GroupLayout(ActionPanel);
        ActionPanel.setLayout(ActionPanelLayout);
        ActionPanelLayout.setHorizontalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SearchActionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HistoryActionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ActionPanelLayout.setVerticalGroup(
            ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SearchActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HistoryActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SearchBody.add(ActionPanel, java.awt.BorderLayout.CENTER);

        AddNewWordBody.setBackground(new java.awt.Color(170, 189, 172));
        AddNewWordBody.setLayout(new java.awt.BorderLayout());
        AddNewWordBody.setVisible(false);

        jPanel9.setBackground(new java.awt.Color(170, 189, 172));

        jPanel10.setBackground(new java.awt.Color(118, 65, 65));

        jButton8.setBackground(new java.awt.Color(0, 255, 0));
        jButton8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Add");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        resetBtn.setBorder(new RoundBtn(30));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AddNewWordBody.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel11.setBackground(new java.awt.Color(153, 255, 153));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jPanel12.setBackground(new java.awt.Color(170, 189, 172));

        jPanel13.setBackground(new java.awt.Color(255, 155, 113));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel13.setForeground(new java.awt.Color(255, 155, 113));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("New word");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        textInputWordAdd.setBackground(new java.awt.Color(255, 255, 255));
        textInputWordAdd.setColumns(20);
        textInputWordAdd.setRows(5);
        textInputWordAdd.setFont( textInputWordAdd.getFont().deriveFont(textInputWordAdd.getFont().getSize() + 5.0f) );
        jScrollPane3.setViewportView(textInputWordAdd);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel12);

        jPanel14.setBackground(new java.awt.Color(170, 189, 172));

        jPanel15.setBackground(new java.awt.Color(255, 155, 113));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel15.setForeground(new java.awt.Color(255, 155, 113));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Definition");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        textInputDefinitionAdd.setBackground(new java.awt.Color(255, 255, 255));
        textInputDefinitionAdd.setColumns(20);
        textInputDefinitionAdd.setRows(5);
        textInputDefinitionAdd.setFont( textInputDefinitionAdd.getFont().deriveFont(textInputDefinitionAdd.getFont().getSize() + 5.0f) );
        jScrollPane4.setViewportView(textInputDefinitionAdd);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel14);

        AddNewWordBody.add(jPanel11, java.awt.BorderLayout.CENTER);

        QuizBody.setBackground(new java.awt.Color(170, 189, 172));
        QuizBody.setLayout(new java.awt.GridLayout());

        jPanel7.setBackground(new java.awt.Color(170, 189, 172));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(170, 189, 172));

        jScrollPane9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        textPaneQuestion.setEditable(false);
        textPaneQuestion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane9.setViewportView(textPaneQuestion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel21.setBackground(new java.awt.Color(170, 189, 172));
        jPanel21.setLayout(new java.awt.GridLayout(2, 0));

        jPanel23.setBackground(new java.awt.Color(170, 189, 172));

        answerA.setBackground(java.awt.Color.pink);
        answerA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        answerA.setForeground(new java.awt.Color(0, 0, 0));
        answerA.setText("jToggleButton1");
        answerA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerA, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerA, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel21.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(170, 189, 172));

        answerC.setBackground(java.awt.Color.pink);
        answerC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        answerC.setForeground(new java.awt.Color(0, 0, 0));
        answerC.setText("jToggleButton2");
        answerC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerC, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(answerC, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel21.add(jPanel24);

        jPanel7.add(jPanel21, java.awt.BorderLayout.CENTER);

        QuizBody.add(jPanel7);

        jPanel20.setBackground(new java.awt.Color(170, 189, 172));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel25.setBackground(new java.awt.Color(170, 189, 172));

        typeOfQuizComboBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        typeOfQuizComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quiz by word", "Quiz by definition" }));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(typeOfQuizComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typeOfQuizComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel25, java.awt.BorderLayout.PAGE_START);

        jPanel26.setBackground(new java.awt.Color(170, 189, 172));
        jPanel26.setLayout(new java.awt.GridLayout(2, 0));

        jPanel27.setBackground(new java.awt.Color(170, 189, 172));

        answerB.setBackground(java.awt.Color.pink);
        answerB.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        answerB.setForeground(new java.awt.Color(0, 0, 0));
        answerB.setText("jToggleButton1");
        answerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerB, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerB, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel26.add(jPanel27);

        jPanel28.setBackground(new java.awt.Color(170, 189, 172));

        answerD.setBackground(java.awt.Color.pink);
        answerD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        answerD.setForeground(new java.awt.Color(0, 0, 0));
        answerD.setText("jToggleButton2");
        answerD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                answerDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerD, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(answerD, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel26.add(jPanel28);

        jPanel20.add(jPanel26, java.awt.BorderLayout.CENTER);

        QuizBody.add(jPanel20);

        jPanel6.setBackground(new java.awt.Color(170, 189, 172));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel29.setBackground(new java.awt.Color(170, 189, 172));

        textScore.setBackground(new java.awt.Color(170, 189, 172));
        textScore.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        textScore.setForeground(new java.awt.Color(204, 0, 51));
        textScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textScore.setText("Your scores: 0");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textScore, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textScore)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel29, java.awt.BorderLayout.PAGE_START);

        jPanel30.setBackground(new java.awt.Color(170, 189, 172));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Skip");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Next");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.add(jPanel30, java.awt.BorderLayout.PAGE_END);

        jPanel31.setBackground(new java.awt.Color(170, 189, 172));

        checkAnswerBtn.setBackground(new java.awt.Color(204, 255, 153));
        checkAnswerBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        checkAnswerBtn.setForeground(new java.awt.Color(0, 0, 0));
        checkAnswerBtn.setText("Check your answer");
        checkAnswerBtn.setEnabled(false);
        checkAnswerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAnswerBtnMouseClicked(evt);
            }
        });

        checkAnsPanel.setBackground(new java.awt.Color(170, 189, 172));
        checkAnsPanel.setVisible(false);

        textOutputCheckAnswer.setEditable(false);
        textOutputCheckAnswer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane8.setViewportView(textOutputCheckAnswer);

        javax.swing.GroupLayout checkAnsPanelLayout = new javax.swing.GroupLayout(checkAnsPanel);
        checkAnsPanel.setLayout(checkAnsPanelLayout);
        checkAnsPanelLayout.setHorizontalGroup(
            checkAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8)
        );
        checkAnsPanelLayout.setVerticalGroup(
            checkAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkAnsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkAnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkAnswerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkAnswerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel31, java.awt.BorderLayout.CENTER);

        QuizBody.add(jPanel6);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddNewWordBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SearchBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(QuizBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddNewWordBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SearchBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(QuizBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Navside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Navside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetBtnActionPerformed

    private void Navlink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Navlink1MouseClicked
        ClickSearchNavlink();
    }//GEN-LAST:event_Navlink1MouseClicked

    private void Navlink2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Navlink2MouseClicked
        SearchBody.setVisible(false);
        AddNewWordBody.setVisible(true);
    }//GEN-LAST:event_Navlink2MouseClicked

    private void Navlink3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Navlink3MouseClicked
        // TODO add your handling code here:
        ClickQuizNavlink(0);
    }//GEN-LAST:event_Navlink3MouseClicked

    private void Navlink4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Navlink4MouseClicked
        // TODO add your handling code here:
        ClickQuizNavlink(1);

    }//GEN-LAST:event_Navlink4MouseClicked

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void randomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randomBtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void historyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyBtnMouseClicked
        // TODO add your handling code here:
        ClickHistoryBtn();
        textOutputHistory.setText(history.getData());
    }//GEN-LAST:event_historyBtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
        if (SearchActionPanel.isVisible()) {
            String inputWord = textInputSearch.getText();
            String inputDefinition = textOutputSearch.getText();

            textInputWordEdit.setText(inputWord.trim().replaceAll(" +", " "));
            textInputDefinitionEdit.setText(inputDefinition.trim().replaceAll(" +", " "));
        }

        ClickEditBtn();

    }//GEN-LAST:event_editBtnMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        // TODO add your handling code here:
        String inputSearch = textInputSearch.getText().trim().replaceAll(" +", " ");
        if ("".equals(inputSearch)) {
            JOptionPane.showMessageDialog(this, "Please enter something!");
            return;
        }

        int idSearchBy = SearchByComboBox.getSelectedIndex();

        Search(inputSearch, idSearchBy);

        history.SaveHistory(inputSearch);
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String inputSearch = textInputSearch.getText().trim().replaceAll(" +", " ");
        if ("".equals(inputSearch)) {
            JOptionPane.showMessageDialog(this, "Please enter something!");
            return;
        }

        int idSearchBy = SearchByComboBox.getSelectedIndex();

        Search(inputSearch, idSearchBy);
        ClickSearchNavlink();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        ClickSearchNavlink();
    }//GEN-LAST:event_jButton4MouseClicked

    private void SaveEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveEditMouseClicked
        // TODO add your handling code here:

        String inputWordEdit = textInputWordEdit.getText();
        String inputDefinitionEdit = textInputDefinitionEdit.getText();
        boolean canSave = true;
        if ("".equals(inputWordEdit.trim())) {
            JOptionPane.showMessageDialog(this, "Please fill in Slang word!");
            canSave = false;
        } else if ("".equals(inputDefinitionEdit.trim())) {
            JOptionPane.showMessageDialog(this, "Please fill in Definition!");
            canSave = false;
        }
        if (canSave) {
            boolean result = dictionary.Update(inputWordEdit, inputDefinitionEdit);
            if (result) {
                JOptionPane.showMessageDialog(this, "Success!");
            } else {
                JOptionPane.showMessageDialog(this, "Failure!");
            }
        }
    }//GEN-LAST:event_SaveEditMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
//JOptionPane.showMessageDialog(this, "Please enter something!");
//JOptionPane.showConfirmDialog(this, Header)

        if (SearchActionPanel.isVisible()) {
            int idSearchBy = SearchByComboBox.getSelectedIndex();
            if (idSearchBy == 1) {
                JOptionPane.showMessageDialog(this, "Firstly, using Search by Slang word to search for which word you want to delete!");
            } else {
                String word = textInputSearch.getText().trim().replaceAll(" +", " ");
                if ("".equals(word)) {
                    JOptionPane.showMessageDialog(this, "Please fill in Search input!");
                } else {
                    int a = JOptionPane.showConfirmDialog(this, "Are you sure to delete \"" + word + "\"?");
                    if (a == JOptionPane.YES_OPTION) {
                        int deleteResult = dictionary.Delete(word);
                        if (deleteResult == -1) {
                            JOptionPane.showMessageDialog(this, "Delete failure!");
                        } else if (deleteResult == 0) {
                            JOptionPane.showMessageDialog(this, "\"" + word + "\" is not exist in system!");
                        } else if (deleteResult == 1) {
                            JOptionPane.showMessageDialog(this, "Delete success!");
                            textOutputSearch.setText("");
                        }
                    }

                }
            }
        } else {
            ClickSearchNavlink();
            int idSearchBy = SearchByComboBox.getSelectedIndex();
            if (idSearchBy == 1) {
                JOptionPane.showMessageDialog(this, "Firstly, using Search by Slang word to search for which word you want to delete!");
            } else {
                String word = textInputSearch.getText().trim().replaceAll(" +", " ");
                if ("".equals(word)) {
                    JOptionPane.showMessageDialog(this, "Please fill in Search input!");
                } else {
                    int a = JOptionPane.showConfirmDialog(this, "Are you sure to delete \"" + word + "\"?");
                    if (a == JOptionPane.YES_OPTION) {
                        int deleteResult = dictionary.Delete(word);
                        if (deleteResult == -1) {
                            JOptionPane.showMessageDialog(this, "Delete failure!");
                        } else if (deleteResult == 0) {
                            JOptionPane.showMessageDialog(this, "\"" + word + "\" is not exist in system!");
                        } else if (deleteResult == 1) {
                            JOptionPane.showMessageDialog(this, "Delete success!");
                            textOutputSearch.setText("");
                        }
                    }

                }
            }
        }

    }//GEN-LAST:event_deleteBtnMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String inputWordAdd = textInputWordAdd.getText().trim().replaceAll(" +", " ");;
        String inputDefinitionAdd = textInputDefinitionAdd.getText().trim().replaceAll(" +", " ");

        if (dictionary.isExistWord(inputWordAdd)) {
            int a = JOptionPane.showConfirmDialog(this, "\"" + inputWordAdd + "\" is already exist in dictionary, do you want to update it?");
            if (a == JOptionPane.YES_OPTION) {
                String def = dictionary.searchBySlangword(inputWordAdd);
                textInputWordEdit.setText(inputWordAdd);
                textInputDefinitionEdit.setText(def);
                ClickEditBtn();
            }
        } else {
            boolean isAdded = dictionary.Add(inputWordAdd, inputDefinitionAdd);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Add success!");
            } else {
                JOptionPane.showMessageDialog(this, "Add failure!");

            }
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void randomBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_randomBtnMouseClicked
        // TODO add your handling code here:
        String[] randomWord = dictionary.randomWord();
        textInputSearch.setText(randomWord[0]);
        textOutputSearch.setText(randomWord[1]);
        ClickSearchNavlink();

    }//GEN-LAST:event_randomBtnMouseClicked

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Are you sure to reset your dictionary to origin?");
        if (a == JOptionPane.YES_OPTION) {
            dictionary.ResetToOriginal();
        }
    }//GEN-LAST:event_resetBtnMouseClicked

    private void answerAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerAMouseClicked
        // TODO add your handling code here:
        chooseAns(0);
    }//GEN-LAST:event_answerAMouseClicked

    private void answerBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerBMouseClicked
        // TODO add your handling code here:
        chooseAns(1);
    }//GEN-LAST:event_answerBMouseClicked

    private void answerCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerCMouseClicked
        // TODO add your handling code here:
        chooseAns(2);
    }//GEN-LAST:event_answerCMouseClicked

    private void answerDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_answerDMouseClicked
        // TODO add your handling code here:
        chooseAns(3);
    }//GEN-LAST:event_answerDMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if (!isCheck) {
            int a = JOptionPane.showConfirmDialog(this, "You didn't check this question, do you want to skip?");
            if (a == JOptionPane.YES_OPTION) {
                int type = typeOfQuizComboBox.getSelectedIndex();
                nextQuestion(type);
            }
        } else {
            int type = typeOfQuizComboBox.getSelectedIndex();
            nextQuestion(type);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int type = typeOfQuizComboBox.getSelectedIndex();
        nextQuestion(type);
    }//GEN-LAST:event_jButton3MouseClicked

    private void checkAnswerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAnswerBtnMouseClicked
        // TODO add your handling code here:
        isCheck = true;
        if (curAns == -1) {
            JOptionPane.showMessageDialog(this, "Please choose an answer!");
            checkAnsPanel.setVisible(false);
        } else if (ansIndex[curAns] == 1) {
            String textOutputChecking = "--> Correct <---";

            textOutputCheckAnswer.setText(textOutputChecking);
            numAnsCorrect++;
            textScore.setText("Your score: " + numAnsCorrect);
            checkAnsPanel.setVisible(true);
        } else {
            String textOutputChecking = "--> Wrong :( <---\n";
            textOutputChecking += patternQuiz[0] + " :" + patternQuiz[1];
            textOutputCheckAnswer.setText(textOutputChecking);
            checkAnsPanel.setVisible(true);
        }
    }//GEN-LAST:event_checkAnswerBtnMouseClicked

    private void Search(String inputSearch, int idSearchBy) {
        if (idSearchBy == 0) {
            // Search by slang word
//            JOptionPane.showMessageDialog(this, "Search by Slang word :" + inputSearch);
            String result = dictionary.searchBySlangword(inputSearch);
            if (result == null) {
                JOptionPane.showMessageDialog(this, "No result match with " + inputSearch);

            } else {
                textOutputSearch.setText(result);
            }

//            StyledDocument doc = jScrollPane2.getStyledDocument();
//            SimpleAttributeSet center = new SimpleAttributeSet();
//            StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
//            doc.setParagraphAttributes(0, doc.getLength(), center, false);
        } else if (idSearchBy == 1) {
            // Search by definition
//            JOptionPane.showMessageDialog(this, "Search by definition :" + inputSearch);
            String result = dictionary.searchByDefinition(inputSearch);

            textOutputSearch.setText(result);
            String[] inputWords = inputSearch.split(" ");
            for (String inputWord : inputWords) {
                highlight(textOutputSearch, inputWords);

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        dictionary.getData();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

// Creates highlights around all occurrences of pattern in textComp
    public void highlight(JTextComponent textComp, String[] pattern) {
        // First remove all old highlights
        removeHighlights(textComp);

        try {
            Highlighter hilite = textComp.getHighlighter();
            Document doc = textComp.getDocument();
            String text = doc.getText(0, doc.getLength());
            int pos = 0;

            // Search for pattern
            // see I have updated now its not case sensitive
            for (String wordHighlight : pattern) {
                while ((pos = text.toUpperCase().indexOf(wordHighlight.toUpperCase(), pos)) >= 0) {
                    // Create highlighter using private painter and apply around pattern
                    hilite.addHighlight(pos, pos + wordHighlight.length(), myHighlightPainter);
                    pos += wordHighlight.length();
                }
            }

        } catch (BadLocationException e) {
        }
    }

// Removes only our private highlights
    public void removeHighlights(JTextComponent textComp) {
        Highlighter hilite = textComp.getHighlighter();
        Highlighter.Highlight[] hilites = hilite.getHighlights();
        for (int i = 0; i < hilites.length; i++) {
            if (hilites[i].getPainter() instanceof MyHighlightPainter) {
                hilite.removeHighlight(hilites[i]);
            }
        }
    }

    void setUpQuiz(int type) {
        checkAnsPanel.setVisible(false);
        isCheck = false;
        curAns = -1;
        chooseAns(-1);
        numAnsCorrect = 0;
        textScore.setText("Your score: " + numAnsCorrect);

        typeOfQuizComboBox.setSelectedIndex(type);
        patternQuiz = dictionary.quiz(type);
        ansIndex = dictionary.quizAns();
        if (type == 0) {

            textPaneQuestion.setText("Definition of " + patternQuiz[0] + "?");
            String[] highlightWord = {patternQuiz[0]};
            highlight(textPaneQuestion, highlightWord);

            answerA.setText(patternQuiz[ansIndex[0]]);
            answerB.setText(patternQuiz[ansIndex[1]]);
            answerC.setText(patternQuiz[ansIndex[2]]);
            answerD.setText(patternQuiz[ansIndex[3]]);
        } else {
            textPaneQuestion.setText("Slang word means " + patternQuiz[0] + "?");
            String[] highlightWord = {patternQuiz[0]};
            highlight(textPaneQuestion, highlightWord);

            answerA.setText(patternQuiz[ansIndex[0]]);
            answerB.setText(patternQuiz[ansIndex[1]]);
            answerC.setText(patternQuiz[ansIndex[2]]);
            answerD.setText(patternQuiz[ansIndex[3]]);
        }

    }

    void nextQuestion(int type) {
        checkAnsPanel.setVisible(false);
        isCheck = false;
        curAns = -1;
        chooseAns(-1);
        typeOfQuizComboBox.setSelectedIndex(type);
        patternQuiz = dictionary.quiz(type);
        ansIndex = dictionary.quizAns();
        if (type == 0) {

            textPaneQuestion.setText("Definition of " + patternQuiz[0] + "?");
            String[] highlightWord = {patternQuiz[0]};
            highlight(textPaneQuestion, highlightWord);

            answerA.setText(patternQuiz[ansIndex[0]]);
            answerB.setText(patternQuiz[ansIndex[1]]);
            answerC.setText(patternQuiz[ansIndex[2]]);
            answerD.setText(patternQuiz[ansIndex[3]]);
        } else {
            textPaneQuestion.setText("Slang word means " + patternQuiz[0] + "?");
            String[] highlightWord = {patternQuiz[0]};
            highlight(textPaneQuestion, highlightWord);

            answerA.setText(patternQuiz[ansIndex[0]]);
            answerB.setText(patternQuiz[ansIndex[1]]);
            answerC.setText(patternQuiz[ansIndex[2]]);
            answerD.setText(patternQuiz[ansIndex[3]]);
        }

    }

    private void myInit() {
        QuizBody.setVisible(false);
        SearchBody.setVisible(true);
        AddNewWordBody.setVisible(false);

        SearchActionPanel.setVisible(true);
        EditActionPanel.setVisible(false);
//        EditActionPanel1.setVisible(false);
    }

    private void ClickQuizNavlink(int type) {
        setUpQuiz(type);

        QuizBody.setVisible(true);
        SearchBody.setVisible(false);
        AddNewWordBody.setVisible(false);

        SearchActionPanel.setVisible(false);
        EditActionPanel.setVisible(false);
        HistoryActionPanel.setVisible(false);
    }

    private void ClickSearchNavlink() {
        QuizBody.setVisible(false);
        SearchBody.setVisible(true);
        AddNewWordBody.setVisible(false);

        SearchActionPanel.setVisible(true);
        EditActionPanel.setVisible(false);
        HistoryActionPanel.setVisible(false);

//        EditActionPanel1.setVisible(false);
    }

    private void ClickEditBtn() {
        QuizBody.setVisible(false);
        SearchBody.setVisible(true);
        AddNewWordBody.setVisible(false);

        SearchActionPanel.setVisible(false);
        EditActionPanel.setVisible(true);
        HistoryActionPanel.setVisible(false);

//        EditActionPanel1.setVisible(false);
    }

    private void ClickHistoryBtn() {
        QuizBody.setVisible(false);
        SearchBody.setVisible(true);
        AddNewWordBody.setVisible(false);

        SearchActionPanel.setVisible(false);
        EditActionPanel.setVisible(false);
        HistoryActionPanel.setVisible(true);
//        EditActionPanel1.setVisible(true);
    }

    private void chooseAns(int ans) {
        javax.swing.JToggleButton[] ansBtn = new javax.swing.JToggleButton[4];
        ansBtn[0] = answerA;
        ansBtn[1] = answerB;
        ansBtn[2] = answerC;
        ansBtn[3] = answerD;
        for (int i = 0; i < 4; i++) {
            if (i == ans) {
                ansBtn[i].setBackground(Color.CYAN);
            } else {
                ansBtn[i].setBackground(Color.PINK);
            }
        }
        curAns = ans;
        if (ans != -1) {
            checkAnswerBtn.setEnabled(true);
        }
    }

//    private void ClickBackToSearchBtn() {
//        SearchActionPanel.setVisible(false);
//        EditActionPanel.setVisible(false);
//        HistoryPanel.setVisible(true);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActionBtn;
    private javax.swing.JPanel ActionPanel;
    private javax.swing.JPanel AddNewWordBody;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel EditActionPanel;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HistoryActionPanel;
    private javax.swing.JPanel Navlink1;
    private javax.swing.JPanel Navlink2;
    private javax.swing.JPanel Navlink3;
    private javax.swing.JPanel Navlink4;
    private javax.swing.JPanel Navside;
    private javax.swing.JPanel QuizBody;
    private javax.swing.JButton SaveEdit;
    private javax.swing.JPanel SearchActionPanel;
    private javax.swing.JPanel SearchBody;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> SearchByComboBox;
    private javax.swing.JToggleButton answerA;
    private javax.swing.JToggleButton answerB;
    private javax.swing.JToggleButton answerC;
    private javax.swing.JToggleButton answerD;
    private javax.swing.JPanel checkAnsPanel;
    private javax.swing.JButton checkAnswerBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton historyBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton randomBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextArea textInputDefinitionAdd;
    private javax.swing.JTextArea textInputDefinitionEdit;
    private javax.swing.JTextArea textInputSearch;
    private javax.swing.JTextArea textInputWordAdd;
    private javax.swing.JTextArea textInputWordEdit;
    private javax.swing.JTextPane textOutputCheckAnswer;
    private javax.swing.JTextArea textOutputHistory;
    private javax.swing.JTextPane textOutputSearch;
    private javax.swing.JTextPane textPaneQuestion;
    private javax.swing.JLabel textScore;
    private javax.swing.JComboBox<String> typeOfQuizComboBox;
    // End of variables declaration//GEN-END:variables

    Highlighter.HighlightPainter myHighlightPainter = new MyHighlightPainter(Color.yellow);
    int curAns = -1;
    int numAnsCorrect = 0;
    boolean isCheck = false;
    String[] patternQuiz;
    int[] ansIndex;
}

// A private subclass of the default highlight painter
class MyHighlightPainter extends DefaultHighlighter.DefaultHighlightPainter {

    public MyHighlightPainter(Color color) {
        super(color);
    }
}
